//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class JsonSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static JsonSettings defaultInstance = ((JsonSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new JsonSettings())));
        
        public static JsonSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://weather.livedoor.com/forecast/webservice/json/v1?city=400040")]
        public string JsonUrl {
            get {
                return ((string)(this["JsonUrl"]));
            }
            set {
                this["JsonUrl"] = value;
            }
        }
    }
}
