//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class NotificationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static NotificationSettings defaultInstance = ((NotificationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NotificationSettings())));
        
        public static NotificationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}\\WindowsPowerShell\\v1.0\\powershell.exe")]
        public string NotificationAppID {
            get {
                return ((string)(this["NotificationAppID"]));
            }
            set {
                this["NotificationAppID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\img\\favicon.ico")]
        public string NotificationIconPath {
            get {
                return ((string)(this["NotificationIconPath"]));
            }
            set {
                this["NotificationIconPath"] = value;
            }
        }
    }
}
